In [1]:
import sqlite3
import pandas as pd

In [3]:
conn = sqlite3.connect("murder.db")

In [5]:
crime_scene_report = pd.read_csv("Data/crime scene report.csv")
drivers_license = pd.read_csv("Data/drivers license.csv")
fb_event_checkin = pd.read_csv("Data/fb event checkin.csv")
get_fit_now_checkin = pd.read_csv("Data/get fit now checkin.csv")
get_fit_now_member = pd.read_csv("Data/get fit now member.csv")
income = pd.read_csv("Data/income.csv")
interview = pd.read_csv("Data/interview.csv")
person = pd.read_csv("Data/person.csv")

In [7]:
crime_scene_report.to_sql("crime_scene_report", conn, if_exists="replace", index=False)
drivers_license.to_sql("drivers_license", conn, if_exists="replace", index=False)
fb_event_checkin.to_sql("fb_event_checkin", conn, if_exists="replace", index=False)
get_fit_now_checkin.to_sql("get_fit_now_checkin", conn, if_exists="replace", index=False)
get_fit_now_member.to_sql("get_fit_now_member", conn, if_exists="replace", index=False)
income.to_sql("income", conn, if_exists="replace", index=False)
interview.to_sql("interview", conn, if_exists="replace", index=False)
person.to_sql("person", conn, if_exists="replace", index=False)

10011

A crime has taken place and the detective needs your help. The detective gave you the crime scene report, but you somehow lost it. You vaguely remember that the crime was a murder that occurred sometime on Jan. 15, 2018 and that it took place in SQL City. All the clues to this mystery are buried in a huge database, and you need to use SQL to navigate through this vast network of information. Your first step to solving the mystery is to retrieve the corresponding crime scene report from the police department's database.

In [9]:
pd.read_sql_query("""
SELECT * from crime_scene_report
limit 5
""", conn)

,date,type,description,city
0,20180115,robbery,A Man Dressed as Spider-Man Is on a Robbery Spree,NYC
1,20180115,murder,Life? Dont talk to me about life.,Albany
2,20180115,murder,"Mama, I killed a man, put a gun against his he...",Reno
3,20180215,murder,REDACTED REDACTED REDACTED,SQL City
4,20180215,murder,Someone killed the guard! He took an arrow to ...,SQL City

In [11]:
pd.set_option('display.max_colwidth', None)

In [13]:
pd.read_sql_query("""
SELECT * from crime_scene_report where type = 'murder' and city = 'SQL City' and date = '20180115'
""", conn)

,date,type,description,city
0,20180115,murder,"Security footage shows that there were 2 witnesses. The first witness lives at the last house on ""Northwestern Dr"". The second witness, named Annabel, lives somewhere on ""Franklin Ave"".",SQL City

In [15]:
pd.read_sql_query("""
SELECT * from person
""", conn)

,id,name,license_id,address_number,address_street_name,ssn
0,10000,Christoper Peteuil,993845,624,Bankhall Ave,747714076
1,10007,Kourtney Calderwood,861794,2791,Gustavus Blvd,477972044
2,10010,Muoi Cary,385336,741,Northwestern Dr,828638512
3,10016,Era Moselle,431897,1987,Wood Glade St,614621061
4,10025,Trena Hornby,550890,276,Daws Hill Way,223877684
...,...,...,...,...,...,...
10006,99936,Luba Benser,274427,680,Carnage Blvd,685095054
10007,99941,Roxana Mckimley,975942,1613,Gate St,512136801
10008,99965,Cherie Zeimantz,287627,3661,The Water Ave,362877324
10009,99982,Allen Cruse,251350,3126,N Jean Dr,348734531
10010,99990,Vance Hunten,830407,3056,Lancefield St,896677562

In [17]:
pd.read_sql_query("""
SELECT * from person
where address_street_name = 'Northwestern Dr' order by address_number desc
limit 5""", conn)

,id,name,license_id,address_number,address_street_name,ssn
0,14887,Morty Schapiro,118009,4919,Northwestern Dr,111564949
1,17729,Lasonya Wildey,439686,3824,Northwestern Dr,917817122
2,53890,Sophie Tiberio,957671,3755,Northwestern Dr,442830147
3,73368,Torie Thalmann,773862,3697,Northwestern Dr,341559436
4,96595,Coretta Cubie,303645,3631,Northwestern Dr,378403829

In [19]:
pd.read_sql_query("""
SELECT * from person
where address_street_name = 'Franklin Ave' and name like '%Annabel%'
""", conn)

,id,name,license_id,address_number,address_street_name,ssn
0,16371,Annabel Miller,490173,103,Franklin Ave,318771143

In [21]:
pd.read_sql_query("""
SELECT * from interview
limit 5
""", conn)

,person_id,transcript
0,28508,‘I deny it!’ said the March Hare.\n
1,63713,\n
2,86208,"way, and the whole party swam to the shore.\n"
3,35267,"lessons in here? Why, there’s hardly room for YOU, and no room at all\n"
4,33856,\n

In [23]:
pd.read_sql_query("""
SELECT * from interview
where person_id in (14887, 16371)
""", conn)

,person_id,transcript
0,14887,"I heard a gunshot and then saw a man run out. He had a ""Get Fit Now Gym"" bag. The membership number on the bag started with ""48Z"". Only gold members have those bags. The man got into a car with a plate that included ""H42W""."
1,16371,"I saw the murder happen, and I recognized the killer from my gym when I was working out last week on January the 9th."

In [25]:
pd.read_sql_query("""
SELECT * from get_fit_now_member
limit 5
""", conn)

,id,person_id,name,membership_start_date,membership_status
0,NL318,65076,Everette Koepke,20170926,gold
1,AOE21,39426,Noe Locascio,20171005,regular
2,2PN28,63823,Jeromy Heitschmidt,20180215,silver
3,0YJ24,80651,Waneta Wellard,20171206,gold
4,3A08L,32858,Mei Bianchin,20170401,silver

In [27]:
pd.read_sql_query("""
SELECT * from get_fit_now_member
where id like '48Z%' and membership_status = 'gold'
""", conn)

      id  person_id           name  membership_start_date membership_status
0  48Z7A      28819   Joe Germuska               20160305              gold
1  48Z55      67318  Jeremy Bowers               20160101              gold

In [29]:
pd.read_sql_query("""
SELECT * from get_fit_now_checkin
where check_in_date = '20180109' and membership_id like '48Z%'
""", conn)

  membership_id  check_in_date  check_in_time  check_out_time
0         48Z7A       20180109           1600            1730
1         48Z55       20180109           1530            1700

In [31]:
pd.read_sql_query("""
SELECT * from drivers_license
limit 5
""", conn)

,id,age,height,eye_color,hair_color,gender,plate_number,car_make,car_model
0,100280,72,57,brown,red,male,P24L4U,Acura,MDX
1,100460,63,72,brown,brown,female,XF02T6,Cadillac,SRX
2,101029,62,74,green,green,female,VKY5KR,Scion,xB
3,101198,43,54,amber,brown,female,Y5NZ08,Nissan,Rogue
4,101255,18,79,blue,grey,female,5162Z1,Lexus,GS

In [33]:
pd.read_sql_query("""
SELECT * from drivers_license 
where plate_number like '%H42W%'
and gender = 'male'
""", conn)

,id,age,height,eye_color,hair_color,gender,plate_number,car_make,car_model
0,423327,30,70,brown,brown,male,0H42W2,Chevrolet,Spark LS
1,664760,21,71,black,black,male,4H42WR,Nissan,Altima

In [35]:
pd.read_sql_query("""
SELECT * from person
where license_id in (423327,664760)
""", conn)

,id,name,license_id,address_number,address_street_name,ssn
0,51739,Tushar Chandra,664760,312,Phi St,137882671
1,67318,Jeremy Bowers,423327,530,"Washington Pl, Apt 3A",871539279

In [37]:
pd.read_sql_query("""
SELECT * from get_fit_now_member
where person_id in ('51739','67318')
""", conn)

      id  person_id           name  membership_start_date membership_status
0  48Z55      67318  Jeremy Bowers               20160101              gold

In [39]:
pd.read_sql_query("""
SELECT * from interview
where person_id = 67318
""", conn)

,person_id,transcript
0,67318,"I was hired by a woman with a lot of money. I don't know her name but I know she's around 5'5"" (65"") or 5'7"" (67""). She has red hair and she drives a Tesla Model S. I know that she attended the SQL Symphony Concert 3 times in December 2017.\n"

In [41]:
pd.read_sql_query("""
SELECT * from drivers_license
limit 5
""", conn)

,id,age,height,eye_color,hair_color,gender,plate_number,car_make,car_model
0,100280,72,57,brown,red,male,P24L4U,Acura,MDX
1,100460,63,72,brown,brown,female,XF02T6,Cadillac,SRX
2,101029,62,74,green,green,female,VKY5KR,Scion,xB
3,101198,43,54,amber,brown,female,Y5NZ08,Nissan,Rogue
4,101255,18,79,blue,grey,female,5162Z1,Lexus,GS

In [43]:
pd.read_sql_query("""
SELECT * from drivers_license
where car_make = 'Tesla' and car_model like '%S%'
and gender = 'female' and hair_color = 'red' and height between 65 and 67
""", conn)

,id,age,height,eye_color,hair_color,gender,plate_number,car_make,car_model
0,202298,68,66,green,red,female,500123,Tesla,Model S
1,291182,65,66,blue,red,female,08CM64,Tesla,Model S
2,918773,48,65,black,red,female,917UU3,Tesla,Model S

In [45]:
pd.read_sql_query("""
SELECT * from fb_event_checkin 
limit 5
""", conn)

,person_id,event_id,event_name,date
0,28508,5880,Nudists are people who wear one-button suits.\n,20170913
1,63713,3865,but that's because it's the best book on anything for the layman.\n,20171009
2,63713,3999,"If Murphy's Law can go wrong, it will.\n",20170502
3,63713,6436,Old programmers never die. They just branch to a new address.\n,20170926
4,82998,4470,Help a swallow land at Capistrano.\n,20171022

In [47]:
pd.read_sql_query("""
SELECT *
FROM person
WHERE license_id IN ("202298", "291182", "918773");
""", conn)

,id,name,license_id,address_number,address_street_name,ssn
0,78881,Red Korb,918773,107,Camerata Dr,961388910
1,90700,Regina George,291182,332,Maple Ave,337169072
2,99716,Miranda Priestly,202298,1883,Golden Ave,987756388

In [49]:
pd.read_sql_query("""
SELECT person_id, count(*) from fb_event_checkin 
where date like '201712%'
and event_name = 'SQL Symphony Concert' group by person_id having person_id in (78881, 90700, 99716)
""", conn)

   person_id  count(*)
0      99716         3

In [51]:
pd.read_sql_query("""
SELECT * from person 
where id = '99716'
""", conn)

,id,name,license_id,address_number,address_street_name,ssn
0,99716,Miranda Priestly,202298,1883,Golden Ave,987756388